### ISSUE TITLE
checklist for next release

### ISSUE THREAD

**Issue by Brett824** [Hyphen-ated/RebirthItemTracker#1]
- [x] update item descriptions to reflect newly found info ("hidden" stat ups found on old items, various nits)
- [x] some method of floor splits
- [ ] dmg calculator ???
- [x] better error messages (log.txt not found, etc)
- [x] reword instructions to avoid issues with placing the item tracker in the wrong directory

**Comment by Brett824** [comment]
@Hyphen-ated @Brett824

**Comment by Brett824** [comment]
4/5 aint bad.
